ERROR - 2021-05-30 16:51:12 --> ErrorException: SQLite3::query(): Unable to prepare statement: 1, no such table: db_student in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/SQLite3/Connection.php:147
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'SQLite3::query(...', '/Applications/X...', 147, Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/SQLite3/Connection.php(147): SQLite3->query('SELECT COUNT(*)...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\SQLite3\Connection->execute('SELECT COUNT(*)...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(373): CodeIgniter\Database\BaseBuilder->countAllResults()
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/tests/App/Database/DatabaseTest.php(14): CodeIgniter\Test\CIDatabaseTestCase->seeInDatabase('student', Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1526): App\Database\DatabaseTest->testSeeInDb()
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1132): PHPUnit\Framework\TestCase->runTest()
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(884): PHPUnit\Framework\TestResult->run(Object(App\Database\DatabaseTest))
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(667): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#15 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#16 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#17 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#18 {main}
ERROR - 2021-05-30 16:52:28 --> ErrorException: SQLite3::query(): Unable to prepare statement: 1, no such table: db_student in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/SQLite3/Connection.php:147
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'SQLite3::query(...', '/Applications/X...', 147, Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/SQLite3/Connection.php(147): SQLite3->query('SELECT COUNT(*)...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\SQLite3\Connection->execute('SELECT COUNT(*)...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(373): CodeIgniter\Database\BaseBuilder->countAllResults()
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/tests/App/Database/DatabaseTest.php(14): CodeIgniter\Test\CIDatabaseTestCase->seeInDatabase('student', Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1526): App\Database\DatabaseTest->testSeeInDb()
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1132): PHPUnit\Framework\TestCase->runTest()
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(884): PHPUnit\Framework\TestResult->run(Object(App\Database\DatabaseTest))
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(667): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#15 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#16 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#17 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#18 {main}
ERROR - 2021-05-30 16:52:48 --> ErrorException: SQLite3::query(): Unable to prepare statement: 1, no such table: db_hi in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/SQLite3/Connection.php:147
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'SQLite3::query(...', '/Applications/X...', 147, Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/SQLite3/Connection.php(147): SQLite3->query('SELECT COUNT(*)...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\SQLite3\Connection->execute('SELECT COUNT(*)...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(373): CodeIgniter\Database\BaseBuilder->countAllResults()
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/tests/App/Database/DatabaseTest.php(14): CodeIgniter\Test\CIDatabaseTestCase->seeInDatabase('hi', Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1526): App\Database\DatabaseTest->testSeeInDb()
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1132): PHPUnit\Framework\TestCase->runTest()
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(884): PHPUnit\Framework\TestResult->run(Object(App\Database\DatabaseTest))
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(667): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#15 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#16 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#17 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#18 {main}
ERROR - 2021-05-30 16:53:41 --> ErrorException: SQLite3::query(): Unable to prepare statement: 1, no such table: student in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/SQLite3/Connection.php:147
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'SQLite3::query(...', '/Applications/X...', 147, Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/SQLite3/Connection.php(147): SQLite3->query('SELECT COUNT(*)...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\SQLite3\Connection->execute('SELECT COUNT(*)...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(373): CodeIgniter\Database\BaseBuilder->countAllResults()
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/tests/App/Database/DatabaseTest.php(14): CodeIgniter\Test\CIDatabaseTestCase->seeInDatabase('student', Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1526): App\Database\DatabaseTest->testSeeInDb()
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1132): PHPUnit\Framework\TestCase->runTest()
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(884): PHPUnit\Framework\TestResult->run(Object(App\Database\DatabaseTest))
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(667): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#15 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#16 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#17 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#18 {main}
ERROR - 2021-05-30 16:56:00 --> mysqli_sql_exception: Table 'ci4.student' doesn't exist in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT COUNT(*)...')
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(373): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/tests/App/Database/DatabaseTest.php(14): CodeIgniter\Test\CIDatabaseTestCase->seeInDatabase('student', Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1526): App\Database\DatabaseTest->testSeeInDb()
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1132): PHPUnit\Framework\TestCase->runTest()
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(884): PHPUnit\Framework\TestResult->run(Object(App\Database\DatabaseTest))
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(667): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#15 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#16 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#17 {main}
ERROR - 2021-05-30 16:56:32 --> ErrorException: SQLite3::query(): Unable to prepare statement: 1, no such table: student in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/SQLite3/Connection.php:147
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'SQLite3::query(...', '/Applications/X...', 147, Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/SQLite3/Connection.php(147): SQLite3->query('SELECT COUNT(*)...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\SQLite3\Connection->execute('SELECT COUNT(*)...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(373): CodeIgniter\Database\BaseBuilder->countAllResults()
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/tests/App/Database/DatabaseTest.php(14): CodeIgniter\Test\CIDatabaseTestCase->seeInDatabase('student', Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1526): App\Database\DatabaseTest->testSeeInDb()
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1132): PHPUnit\Framework\TestCase->runTest()
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(884): PHPUnit\Framework\TestResult->run(Object(App\Database\DatabaseTest))
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(667): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#15 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#16 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#17 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#18 {main}
ERROR - 2021-05-30 16:58:44 --> Error connecting to the database: No such file or directory
ERROR - 2021-05-30 16:58:44 --> Error connecting to the database: No such file or directory
ERROR - 2021-05-30 16:59:07 --> ErrorException: SQLite3::query(): Unable to prepare statement: 1, no such table: student in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/SQLite3/Connection.php:147
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'SQLite3::query(...', '/Applications/X...', 147, Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/SQLite3/Connection.php(147): SQLite3->query('SELECT COUNT(*)...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\SQLite3\Connection->execute('SELECT COUNT(*)...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(373): CodeIgniter\Database\BaseBuilder->countAllResults()
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/tests/App/Database/DatabaseTest.php(14): CodeIgniter\Test\CIDatabaseTestCase->seeInDatabase('student', Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1526): App\Database\DatabaseTest->testSeeInDb()
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1132): PHPUnit\Framework\TestCase->runTest()
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(884): PHPUnit\Framework\TestResult->run(Object(App\Database\DatabaseTest))
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(667): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#15 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#16 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#17 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#18 {main}
ERROR - 2021-05-30 17:00:01 --> Error connecting to the database: No such file or directory
ERROR - 2021-05-30 17:00:01 --> Error connecting to the database: No such file or directory
ERROR - 2021-05-30 17:00:13 --> mysqli_sql_exception: Table 'ci4.db_student' doesn't exist in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT COUNT(*)...')
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(373): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/tests/App/Database/DatabaseTest.php(14): CodeIgniter\Test\CIDatabaseTestCase->seeInDatabase('student', Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1526): App\Database\DatabaseTest->testSeeInDb()
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1132): PHPUnit\Framework\TestCase->runTest()
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(884): PHPUnit\Framework\TestResult->run(Object(App\Database\DatabaseTest))
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(667): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#15 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#16 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#17 {main}
ERROR - 2021-05-30 17:01:03 --> ErrorException: SQLite3::query(): Unable to prepare statement: 1, no such table: db_student in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/SQLite3/Connection.php:147
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'SQLite3::query(...', '/Applications/X...', 147, Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/SQLite3/Connection.php(147): SQLite3->query('SELECT COUNT(*)...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\SQLite3\Connection->execute('SELECT COUNT(*)...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(373): CodeIgniter\Database\BaseBuilder->countAllResults()
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/tests/App/Database/DatabaseTest.php(14): CodeIgniter\Test\CIDatabaseTestCase->seeInDatabase('student', Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1526): App\Database\DatabaseTest->testSeeInDb()
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1132): PHPUnit\Framework\TestCase->runTest()
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(884): PHPUnit\Framework\TestResult->run(Object(App\Database\DatabaseTest))
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(667): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#15 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#16 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#17 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#18 {main}
CRITICAL - 2021-05-30 17:35:03 --> test is not a valid database connection group.
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Common.php(327): CodeIgniter\Database\Config::connect('test', true)
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MigrationRunner.php(150): db_connect(NULL)
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Config/Services.php(443): CodeIgniter\Database\MigrationRunner->__construct(NULL, NULL)
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Config/BaseService.php(100): CodeIgniter\Config\Services::migrations(Object(Config\Migrations), NULL, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Config/Services.php(438): CodeIgniter\Config\BaseService::getSharedInstance('migrations', NULL, NULL)
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Config/BaseService.php(171): CodeIgniter\Config\Services::migrations()
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Commands/Database/Migrate.php(73): CodeIgniter\Config\BaseService::__callStatic('migrations', Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/CommandRunner.php(80): CodeIgniter\CLI\Commands->run('migrate', Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/CommandRunner.php(58): CodeIgniter\CLI\CommandRunner->index(Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(932): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/Console.php(61): CodeIgniter\CodeIgniter->run()
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/spark(66): CodeIgniter\CLI\Console->run()
#15 {main}
CRITICAL - 2021-05-30 17:37:00 --> test is not a valid database connection group.
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Common.php(327): CodeIgniter\Database\Config::connect('test', true)
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MigrationRunner.php(150): db_connect(NULL)
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Config/Services.php(443): CodeIgniter\Database\MigrationRunner->__construct(NULL, NULL)
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Config/BaseService.php(100): CodeIgniter\Config\Services::migrations(Object(Config\Migrations), NULL, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Config/Services.php(438): CodeIgniter\Config\BaseService::getSharedInstance('migrations', NULL, NULL)
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Config/BaseService.php(171): CodeIgniter\Config\Services::migrations()
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Commands/Database/Migrate.php(73): CodeIgniter\Config\BaseService::__callStatic('migrations', Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/CommandRunner.php(80): CodeIgniter\CLI\Commands->run('migrate', Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/CommandRunner.php(58): CodeIgniter\CLI\CommandRunner->index(Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(932): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/Console.php(61): CodeIgniter\CodeIgniter->run()
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/spark(66): CodeIgniter\CLI\Console->run()
#15 {main}
ERROR - 2021-05-30 18:52:52 --> mysqli_sql_exception: Table 'ci4_test.db_student' doesn't exist in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `db...')
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `db...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `db...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/tests/_support/Database/Seeds/TestSeeder.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/Seeder.php(171): App\Database\Seeds\TestSeeder->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(332): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(253): CodeIgniter\Test\CIDatabaseTestCase->seed('TestSeeder')
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(211): CodeIgniter\Test\CIDatabaseTestCase->runSeeds()
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(178): CodeIgniter\Test\CIDatabaseTestCase->setUpSeed()
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/tests/App/Database/DatabaseTest.php(17): CodeIgniter\Test\CIDatabaseTestCase->setUp()
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1125): App\Database\DatabaseTest->setUp()
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(884): PHPUnit\Framework\TestResult->run(Object(App\Database\DatabaseTest))
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#15 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#16 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#17 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(667): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#18 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#19 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#20 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#21 {main}
ERROR - 2021-05-30 18:53:36 --> mysqli_sql_exception: Table 'ci4_test.student' doesn't exist in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `st...')
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `st...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `st...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `st...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/tests/_support/Database/Seeds/TestSeeder.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/Seeder.php(171): App\Database\Seeds\TestSeeder->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(332): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(253): CodeIgniter\Test\CIDatabaseTestCase->seed('TestSeeder')
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(211): CodeIgniter\Test\CIDatabaseTestCase->runSeeds()
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(178): CodeIgniter\Test\CIDatabaseTestCase->setUpSeed()
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/tests/App/Database/DatabaseTest.php(17): CodeIgniter\Test\CIDatabaseTestCase->setUp()
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1125): App\Database\DatabaseTest->setUp()
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(884): PHPUnit\Framework\TestResult->run(Object(App\Database\DatabaseTest))
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#15 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#16 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#17 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(667): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#18 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#19 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#20 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#21 {main}
ERROR - 2021-05-30 19:21:17 --> mysqli_sql_exception: Unknown column 'name' in 'field list' in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `us...')
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(422): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/tests/App/Database/DatabaseTest.php(34): CodeIgniter\Test\CIDatabaseTestCase->hasInDatabase('user', Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1526): App\Database\DatabaseTest->testCanInsertRowInDb()
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1132): PHPUnit\Framework\TestCase->runTest()
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(884): PHPUnit\Framework\TestResult->run(Object(App\Database\DatabaseTest))
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(667): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#15 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#16 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#17 {main}
ERROR - 2021-05-30 19:21:17 --> mysqli_sql_exception: Unknown column 'name' in 'where clause' in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php(314): mysqli->query('DELETE FROM `us...')
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `us...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `us...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(2864): CodeIgniter\Database\BaseConnection->query('DELETE FROM `us...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(231): CodeIgniter\Database\BaseBuilder->delete()
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1178): CodeIgniter\Test\CIDatabaseTestCase->tearDown()
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(884): PHPUnit\Framework\TestResult->run(Object(App\Database\DatabaseTest))
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(667): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#15 {main}
ERROR - 2021-05-30 19:26:59 --> mysqli_sql_exception: Table 'ci4_test.users' doesn't exist in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT `first_n...')
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `first_n...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `first_n...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `first_n...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(396): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/tests/App/Database/DatabaseTest.php(39): CodeIgniter\Test\CIDatabaseTestCase->grabFromDatabase('users', 'first_name', Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1526): App\Database\DatabaseTest->testCanGrabUser()
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1132): PHPUnit\Framework\TestCase->runTest()
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(884): PHPUnit\Framework\TestResult->run(Object(App\Database\DatabaseTest))
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(667): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#15 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#16 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#17 {main}
ERROR - 2021-05-30 19:37:43 --> mysqli_sql_exception: Unknown column 'emaill' in 'field list' in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `us...')
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(422): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/tests/App/Database/DatabaseTest.php(35): CodeIgniter\Test\CIDatabaseTestCase->hasInDatabase('user', Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1526): App\Database\DatabaseTest->testCanInsertRowInUserDb()
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1132): PHPUnit\Framework\TestCase->runTest()
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(884): PHPUnit\Framework\TestResult->run(Object(App\Database\DatabaseTest))
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(667): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#15 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#16 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#17 {main}
ERROR - 2021-05-30 19:37:43 --> mysqli_sql_exception: Unknown column 'emaill' in 'where clause' in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php(314): mysqli->query('DELETE FROM `us...')
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `us...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `us...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(2864): CodeIgniter\Database\BaseConnection->query('DELETE FROM `us...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(231): CodeIgniter\Database\BaseBuilder->delete()
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1178): CodeIgniter\Test\CIDatabaseTestCase->tearDown()
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(884): PHPUnit\Framework\TestResult->run(Object(App\Database\DatabaseTest))
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(667): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#15 {main}
ERROR - 2021-05-30 19:59:00 --> Error connecting to the database: Unknown database 'ci4_test'
CRITICAL - 2021-05-30 19:59:00 --> Unable to connect to the database.
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Model.php(247): CodeIgniter\Database\BaseBuilder->get()
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/app/Models/StudentModel.php(41): CodeIgniter\BaseModel->first()
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/app/Controllers/Student.php(28): App\Models\StudentModel->getStudent('1')
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(936): App\Controllers\Student->view('1')
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Student))
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/public/index.php(44): CodeIgniter\CodeIgniter->run()
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Commands/Server/rewrite.php(45): require_once('/Applications/X...')
#11 {main}
ERROR - 2021-05-30 19:59:50 --> Error connecting to the database: Unknown database 'ci4_test'
ERROR - 2021-05-30 19:59:50 --> Error connecting to the database: Unknown database 'ci4_test'
ERROR - 2021-05-30 19:59:50 --> Error connecting to the database: Unknown database 'ci4_test'
ERROR - 2021-05-30 19:59:50 --> Error connecting to the database: Unknown database 'ci4_test'
ERROR - 2021-05-30 20:01:30 --> Error connecting to the database: Unknown database 'ci4'
CRITICAL - 2021-05-30 20:01:30 --> Unable to connect to the database.
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Model.php(247): CodeIgniter\Database\BaseBuilder->get()
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/app/Models/StudentModel.php(41): CodeIgniter\BaseModel->first()
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/app/Controllers/Student.php(28): App\Models\StudentModel->getStudent('1')
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(936): App\Controllers\Student->view('1')
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Student))
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/public/index.php(44): CodeIgniter\CodeIgniter->run()
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Commands/Server/rewrite.php(45): require_once('/Applications/X...')
#11 {main}
ERROR - 2021-05-30 20:02:06 --> mysqli_sql_exception: Table 'ci4_test.student' doesn't exist in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT *\nFROM `...')
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Model.php(247): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/app/Models/StudentModel.php(41): CodeIgniter\BaseModel->first()
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/app/Controllers/Student.php(28): App\Models\StudentModel->getStudent('1')
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(936): App\Controllers\Student->view('1')
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Student))
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/public/index.php(44): CodeIgniter\CodeIgniter->run()
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Commands/Server/rewrite.php(45): require_once('/Applications/X...')
#13 {main}
CRITICAL - 2021-05-30 20:02:06 --> Table 'ci4_test.student' doesn't exist
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT *\nFROM `...')
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Model.php(247): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/app/Models/StudentModel.php(41): CodeIgniter\BaseModel->first()
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/app/Controllers/Student.php(28): App\Models\StudentModel->getStudent('1')
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(936): App\Controllers\Student->view('1')
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Student))
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/public/index.php(44): CodeIgniter\CodeIgniter->run()
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Commands/Server/rewrite.php(45): require_once('/Applications/X...')
#13 {main}
ERROR - 2021-05-30 20:06:09 --> mysqli_sql_exception: Table 'ci4_test.user' doesn't exist in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT COUNT(*)...')
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Test/CIDatabaseTestCase.php(373): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/tests/App/Database/DatabaseTest.php(26): CodeIgniter\Test\CIDatabaseTestCase->seeInDatabase('user', Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1526): App\Database\DatabaseTest->testSeeInUserDb()
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(1132): PHPUnit\Framework\TestCase->runTest()
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestCase.php(884): PHPUnit\Framework\TestResult->run(Object(App\Database\DatabaseTest))
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(667): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#15 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#16 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#17 {main}
ERROR - 2021-05-30 20:08:17 --> mysqli_sql_exception: Table 'ci4_test.student' doesn't exist in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `st...')
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `st...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `st...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `st...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/app/Database/Seeds/StudentSeeder.php(33): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/Seeder.php(171): App\Database\Seeds\StudentSeeder->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Commands/Database/Seed.php(83): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/CommandRunner.php(80): CodeIgniter\CLI\Commands->run('db:seed', Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/CommandRunner.php(58): CodeIgniter\CLI\CommandRunner->index(Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(932): CodeIgniter\CLI\CommandRunner->_remap('index', 'db:seed', 'StudentSeeder')
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/Console.php(61): CodeIgniter\CodeIgniter->run()
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/spark(66): CodeIgniter\CLI\Console->run()
#15 {main}
ERROR - 2021-05-30 20:08:19 --> mysqli_sql_exception: Table 'ci4_test.user' doesn't exist in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `us...')
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/app/Database/Seeds/UserSeeder.php(30): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/Seeder.php(171): App\Database\Seeds\UserSeeder->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Commands/Database/Seed.php(83): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/CommandRunner.php(80): CodeIgniter\CLI\Commands->run('db:seed', Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/CommandRunner.php(58): CodeIgniter\CLI\CommandRunner->index(Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(932): CodeIgniter\CLI\CommandRunner->_remap('index', 'db:seed', 'UserSeeder')
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/Console.php(61): CodeIgniter\CodeIgniter->run()
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/spark(66): CodeIgniter\CLI\Console->run()
#15 {main}
ERROR - 2021-05-30 20:09:40 --> mysqli_sql_exception: Table 'ci4_test.user' doesn't exist in /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `us...')
#1 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/BaseBuilder.php(2263): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/app/Database/Seeds/UserSeeder.php(30): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Database/Seeder.php(171): App\Database\Seeds\UserSeeder->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/Commands/Database/Seed.php(83): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/CommandRunner.php(80): CodeIgniter\CLI\Commands->run('db:seed', Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/CommandRunner.php(58): CodeIgniter\CLI\CommandRunner->index(Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(932): CodeIgniter\CLI\CommandRunner->_remap('index', 'db:seed', 'UserSeeder')
#11 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#12 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/system/CLI/Console.php(61): CodeIgniter\CodeIgniter->run()
#14 /Applications/XAMPP/xamppfiles/htdocs/xampp-ci/spark(66): CodeIgniter\CLI\Console->run()
#15 {main}
